<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */

declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\LoginHandler::class          => App\Handler\LoginHandlerFactory::class,
            App\Handler\PasswordHandler::class       => App\Handler\PasswordHandlerFactory::class,
            App\Handler\ProfileHandler::class        => App\Handler\ProfileHandlerFactory::class,
            App\Handler\RecoveryCodeHandler::class   => App\Handler\RecoveryCodeHandlerFactory::class,
            App\Middleware\TemplateMiddleware::class => App\Middleware\TemplateMiddlewareFactory::class,
        ],
    ],
];
