<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\API\AccessHandler::class => App\Handler\API\AccessHandlerFactory::class,
            App\Handler\API\ResourceHandler::class => App\Handler\API\ResourceHandlerFactory::class,
            App\Handler\API\RoleHandler::class => App\Handler\API\RoleHandlerFactory::class,
            App\Handler\API\UserHandler::class => App\Handler\API\UserHandlerFactory::class,
            App\Handler\Admin\HomeHandler::class => App\Handler\Admin\HomeHandlerFactory::class,
            App\Handler\Admin\LogHandler::class => App\Handler\Admin\LogHandlerFactory::class,
            App\Handler\Admin\ResourcesHandler::class => App\Handler\Admin\ResourcesHandlerFactory::class,
            App\Handler\Admin\RolesHandler::class => App\Handler\Admin\RolesHandlerFactory::class,
            App\Handler\Admin\UsersHandler::class => App\Handler\Admin\UsersHandlerFactory::class,
            App\Handler\HomePageHandler::class => App\Handler\HomePageHandlerFactory::class,
            App\Handler\LoginHandler::class => App\Handler\LoginHandlerFactory::class,
            App\Handler\PasswordHandler::class => App\Handler\PasswordHandlerFactory::class,
            App\Handler\ProfileHandler::class => App\Handler\ProfileHandlerFactory::class,
            App\Handler\RecoveryCodeHandler::class => App\Handler\RecoveryCodeHandlerFactory::class,
            App\Middleware\AccessMiddleware::class => App\Middleware\AccessMiddlewareFactory::class,
            App\Middleware\DbMiddleware::class => App\Middleware\DbMiddlewareFactory::class,
            App\Middleware\TemplateMiddleware::class => App\Middleware\TemplateMiddlewareFactory::class,
        ],
    ],
];
